### ISSUE TITLE
Lockbox Extensions V2.0

### ISSUE THREAD

**Issue by jrampono** [microsoft/azure-data-services-go-fast-codebase#48]
- [x] Add Synapse Workspace as data sink #33 
- [x] Integrate ADF pipelines into Framework specific Synapse instance #39 
- [x] Make number of IRs configurable #32
